consumes:
  - application/json
produces:
  - application/json
schemes:
  - http
  - ws
swagger: "2.0"
info:
  description: Hashtag backend
  title: Hashtag Service
  version: 0.1.0
basePath: /app/v1
paths:
  /status/alive:
    get:
      tags:
        - health
      summary: Liveness check
      operationId: getLiveness
      responses:
        "200":
          description: OK
          schema:
            type: string
  /status/ready:
    get:
      tags:
        - health
      summary: Readiness check
      operationId: getReadiness
      responses:
        "200":
          description: OK
          schema:
            type: string
  /websocket:
    get:
      tags:
        - websocket
      summary: connect websocket
      schemes:
        - ws
      operationId: connectWebsocket
      responses:
        "200":
          description: OK
          schema:
            type: string
  /user/{username}:
    get:
      tags:
        - user
      operationId: getUserHashtagChannels
      parameters:
        - type: string
          name: username
          in: path
          required: true
      responses:
        "200":
          description: List of user hashtag channels
          schema:
            $ref: "#/definitions/UserHashtagChannels"
        default:
          description: Unexpected error
          schema:
            $ref: "#/definitions/ErrorResponse"
    post:
      tags:
        - user
      operationId: postUserHashtag
      parameters:
        - type: string
          name: username
          in: path
          required: true
        - name: userHashtag
          in: body
          schema:
            $ref: "#/definitions/UserHashtag"
      responses:
        "200":
          description: Hashtag linked to user
          schema:
            $ref: "#/definitions/HashtagResponse"
        default:
          description: Unexpected error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /hashtag/{hashtagId}/messages:
    get:
      tags:
        - hashtags
      operationId: getHashtagMessages
      parameters:
        - type: string
          name: hashtagId
          in: path
          required: true
      responses:
        "200":
          description: List of hashtag messages
          schema:
            $ref: "#/definitions/HashtagMessagesResponse"
        default:
          description: Unexpected error
          schema:
            $ref: "#/definitions/ErrorResponse"
    post:
      tags:
        - hashtags
      operationId: insertHashtagMessage
      parameters:
        - type: string
          name: hashtagId
          in: path
          required: true
        - name: hashtagMessage
          in: body
          required: true
          schema:
            $ref: "#/definitions/Message"
      responses:
        "200":
          description: Hashtag messaged inserted
          schema:
            $ref: "#/definitions/HashtagResponse"
        default:
          description: Unexpected error
          schema:
            $ref: "#/definitions/ErrorResponse"
definitions:
  HashtagMessagesResponse:
    type: object
    properties:
      hashtagId:
        type: string
      messages:
        type: array
        items:
          $ref: "#/definitions/Message"
  Message:
    type: object
    properties:
      id:
        type: string
      username:
        type: string
      created_at:
        type: string
        format: date-time
      content:
        type: string
  HashtagResponse:
    type: object
    properties:
      messageId:
        type: string
  UserHashtagChannels:
    type: array
    items:
      type: string
  UserHashtag:
    type: object
    properties:
      hashtagId:
        type: string
  HashtagResponse:
    type: object
    properties:
      messageId:
        type: string
  ErrorResponse:
    type: object
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string
